#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /api/auth/register
  controller: App\Controller\AuthController::register
  methods: POST

api_get_token:
  path: /api/auth/get_token
  controller: App\Controller\AuthController::getTokenUser

test:
  path: /api/test
  controller: App\Controller\ApiController::testAction
